// import axios from 'axios'

export const state = () => ({
  posts: [
    { id: 1, title: 'Vue, React and Angular', thumbnail: require('~/assets/img/pexels-kevin-ku-577585.jpg'), excerpt: 'The 3 most popular frameworks/libraries out in the industry, you could potentially say they work the same, however, there are subtle differences that may change the way you think when deciding to develop a frontend application.', isFeatured: true, slug:'vue-react-and-angular', content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam tenetur est quidem nostrum non? Dicta facere obcaecati reprehenderit consequuntur delectus, asperiores aperiam cum odit quidem odio voluptatum reiciendis\n\n rem fuga libero nostrum. Dolore alias rerum, veritatis nihil, earum, autem voluptates sed non id reiciendis quo. Esse facilis quis sunt, quo alias placeat consequatur ab tempore natus distinctio perspiciatis maiores possimus deserunt cum, accusamus saepe suscipit animi aperiam quod impedit quasi eius numquam. \n\n Placeat repellendus sint atque corrupti mollitia ducimus amet dignissimos, consectetur doloremque enim nostrum officia vitae iure recusandae quos consequatur temporibus eius? Consequatur minus quis vel minima, enim esse tempore non autem earum accusantium fugiat excepturi nostrum corrupti velit. Itaque ex animi laudantium commodi provident minima accusamus doloribus fuga, magnam asperiores. Reprehenderit earum laudantium dicta! Suscipit quod magnam odit alias! \n\n Corrupti aliquam modi consequuntur cum quaerat autem reprehenderit cupiditate nam enim quis officiis doloribus, dolore ipsam distinctio, ad totam assumenda quos accusamus quasi, cumque minima in earum. Possimus provident perspiciatis pariatur cum, ratione deleniti eos perferendis repellat.\n\n Consectetur, nostrum neque sunt a sint laborum provident corporis rem, molestiae nemo iusto quaerat nisi alias nulla ipsam, dolorem non soluta officia ratione quia quis numquam natus minima blanditiis? Quibusdam, voluptatem.\n\n Excepturi in dolorem, distinctio eos qui illum dolorum neque quo praesentium quas atque, et itaque aliquam accusantium, maiores veritatis tempore.\n\n Aliquid, laudantium itaque ex corporis ut similique explicabo mollitia eum molestiae, doloremque officiis? Natus aliquam quia necessitatibus, perspiciatis suscipit eum enim dolorum voluptatem illo labore vel quas! Iste ex doloribus fuga pariatur officia. Ducimus non cupiditate neque provident corrupti suscipit aut accusantium, commodi cumque. Asperiores recusandae expedita labore corrupti, nemo animi ipsum a doloribus debitis repellendus consectetur autem quisquam totam omnis eos id modi optio dolorum nobis?", date: 1616602286},
    { id: 2, title: 'Choosing a framework', thumbnail: require('~/assets/img/pexels-christina-morillo-1181341.jpg'), excerpt: 'Backend. A word that scares a lot of people. Good news is we managed to put our code in the hands of something simpler: A framework. Which one would you choose?', slug: 'choosing-a-framework', content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam tenetur est quidem nostrum non? Dicta facere obcaecati reprehenderit consequuntur delectus, asperiores aperiam cum odit quidem odio voluptatum reiciendis\n\n rem fuga libero nostrum. Dolore alias rerum, veritatis nihil, earum, autem voluptates sed non id reiciendis quo. Esse facilis quis sunt, quo alias placeat consequatur ab tempore natus distinctio perspiciatis maiores possimus deserunt cum, accusamus saepe suscipit animi aperiam quod impedit quasi eius numquam. \n\n Placeat repellendus sint atque corrupti mollitia ducimus amet dignissimos, consectetur doloremque enim nostrum officia vitae iure recusandae quos consequatur temporibus eius? Consequatur minus quis vel minima, enim esse tempore non autem earum accusantium fugiat excepturi nostrum corrupti velit. Itaque ex animi laudantium commodi provident minima accusamus doloribus fuga, magnam asperiores. Reprehenderit earum laudantium dicta! Suscipit quod magnam odit alias! \n\n Corrupti aliquam modi consequuntur cum quaerat autem reprehenderit cupiditate nam enim quis officiis doloribus, dolore ipsam distinctio, ad totam assumenda quos accusamus quasi, cumque minima in earum. Possimus provident perspiciatis pariatur cum, ratione deleniti eos perferendis repellat.\n\n Consectetur, nostrum neque sunt a sint laborum provident corporis rem, molestiae nemo iusto quaerat nisi alias nulla ipsam, dolorem non soluta officia ratione quia quis numquam natus minima blanditiis? Quibusdam, voluptatem.\n\n Excepturi in dolorem, distinctio eos qui illum dolorum neque quo praesentium quas atque, et itaque aliquam accusantium, maiores veritatis tempore.\n\n Aliquid, laudantium itaque ex corporis ut similique explicabo mollitia eum molestiae, doloremque officiis? Natus aliquam quia necessitatibus, perspiciatis suscipit eum enim dolorum voluptatem illo labore vel quas! Iste ex doloribus fuga pariatur officia. Ducimus non cupiditate neque provident corrupti suscipit aut accusantium, commodi cumque. Asperiores recusandae expedita labore corrupti, nemo animi ipsum a doloribus debitis repellendus consectetur autem quisquam totam omnis eos id modi optio dolorum nobis?", date: 1616602286},
    { id: 3, title: 'Migrating to the cloud', thumbnail: require('~/assets/img/pexels-panumas-nikhomkhai-1148820.jpg'), excerpt: 'The cloud is everywhere, don\'t hesitate to move all your stuff there. But is it that necessary? There are multiple cloud hosting providers out there', slug: 'migrating-to-the-cloud', content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam tenetur est quidem nostrum non? Dicta facere obcaecati reprehenderit consequuntur delectus, asperiores aperiam cum odit quidem odio voluptatum reiciendis\n\n rem fuga libero nostrum. Dolore alias rerum, veritatis nihil, earum, autem voluptates sed non id reiciendis quo. Esse facilis quis sunt, quo alias placeat consequatur ab tempore natus distinctio perspiciatis maiores possimus deserunt cum, accusamus saepe suscipit animi aperiam quod impedit quasi eius numquam. \n\n Placeat repellendus sint atque corrupti mollitia ducimus amet dignissimos, consectetur doloremque enim nostrum officia vitae iure recusandae quos consequatur temporibus eius? Consequatur minus quis vel minima, enim esse tempore non autem earum accusantium fugiat excepturi nostrum corrupti velit. Itaque ex animi laudantium commodi provident minima accusamus doloribus fuga, magnam asperiores. Reprehenderit earum laudantium dicta! Suscipit quod magnam odit alias! \n\n Corrupti aliquam modi consequuntur cum quaerat autem reprehenderit cupiditate nam enim quis officiis doloribus, dolore ipsam distinctio, ad totam assumenda quos accusamus quasi, cumque minima in earum. Possimus provident perspiciatis pariatur cum, ratione deleniti eos perferendis repellat.\n\n Consectetur, nostrum neque sunt a sint laborum provident corporis rem, molestiae nemo iusto quaerat nisi alias nulla ipsam, dolorem non soluta officia ratione quia quis numquam natus minima blanditiis? Quibusdam, voluptatem.\n\n Excepturi in dolorem, distinctio eos qui illum dolorum neque quo praesentium quas atque, et itaque aliquam accusantium, maiores veritatis tempore.\n\n Aliquid, laudantium itaque ex corporis ut similique explicabo mollitia eum molestiae, doloremque officiis? Natus aliquam quia necessitatibus, perspiciatis suscipit eum enim dolorum voluptatem illo labore vel quas! Iste ex doloribus fuga pariatur officia. Ducimus non cupiditate neque provident corrupti suscipit aut accusantium, commodi cumque. Asperiores recusandae expedita labore corrupti, nemo animi ipsum a doloribus debitis repellendus consectetur autem quisquam totam omnis eos id modi optio dolorum nobis?", date: 1616602286},
    { id: 4, title: 'Writing better code', thumbnail: require('~/assets/img/pexels-panumas-nikhomkhai-1148820.jpg'), excerpt: 'A good developer is not only the developer that knows how to code, but the developer that knows how is gonna code in the future', slug: 'writing-better-code', content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam tenetur est quidem nostrum non? Dicta facere obcaecati reprehenderit consequuntur delectus, asperiores aperiam cum odit quidem odio voluptatum reiciendis\n\n rem fuga libero nostrum. Dolore alias rerum, veritatis nihil, earum, autem voluptates sed non id reiciendis quo. Esse facilis quis sunt, quo alias placeat consequatur ab tempore natus distinctio perspiciatis maiores possimus deserunt cum, accusamus saepe suscipit animi aperiam quod impedit quasi eius numquam. \n\n Placeat repellendus sint atque corrupti mollitia ducimus amet dignissimos, consectetur doloremque enim nostrum officia vitae iure recusandae quos consequatur temporibus eius? Consequatur minus quis vel minima, enim esse tempore non autem earum accusantium fugiat excepturi nostrum corrupti velit. Itaque ex animi laudantium commodi provident minima accusamus doloribus fuga, magnam asperiores. Reprehenderit earum laudantium dicta! Suscipit quod magnam odit alias! \n\n Corrupti aliquam modi consequuntur cum quaerat autem reprehenderit cupiditate nam enim quis officiis doloribus, dolore ipsam distinctio, ad totam assumenda quos accusamus quasi, cumque minima in earum. Possimus provident perspiciatis pariatur cum, ratione deleniti eos perferendis repellat.\n\n Consectetur, nostrum neque sunt a sint laborum provident corporis rem, molestiae nemo iusto quaerat nisi alias nulla ipsam, dolorem non soluta officia ratione quia quis numquam natus minima blanditiis? Quibusdam, voluptatem.\n\n Excepturi in dolorem, distinctio eos qui illum dolorum neque quo praesentium quas atque, et itaque aliquam accusantium, maiores veritatis tempore.\n\n Aliquid, laudantium itaque ex corporis ut similique explicabo mollitia eum molestiae, doloremque officiis? Natus aliquam quia necessitatibus, perspiciatis suscipit eum enim dolorum voluptatem illo labore vel quas! Iste ex doloribus fuga pariatur officia. Ducimus non cupiditate neque provident corrupti suscipit aut accusantium, commodi cumque. Asperiores recusandae expedita labore corrupti, nemo animi ipsum a doloribus debitis repellendus consectetur autem quisquam totam omnis eos id modi optio dolorum nobis?", date: 1616602286}
  ],
})

export const getters = {
  allPosts: (state) => state.posts.filter(post => !post.isFeatured),
  getFeaturedPost: (state) => state.posts.filter(post => post.isFeatured)[0],
  getPostTitles: (state) => state.posts.map(post => post.title),
  getPost: (state) => (id) => state.posts.find(post => post.id == id)
}

export const actions = {
  async getPostsTest ({ commit }) {
    const res = await this.$axios.$get('/posts')
  }
}

export const mutations = {}